on:
  pull_request:
    branches:
    - master

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@0.0.20
        with:
          required-ros-distributions: melodic
      - run: /opt/ros/melodic/setup.bash && rosnode --help
