on:
  pull_request:
    branches:
    - master

jobs:
  build_docker:
    strategy:
      matrix:
        ros_distro : [melodic]
        ros_repo: [main]
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v1
      - name: Setup ROS
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{matrix.ros_distro}}
          ROS_REPO: ${{matrix.ros_repo}}
      - run: |
          echo $PWD
          mkdir -p /home/runner/work/lidar_camera_calibration/catkin_ws/lidar_camera_calibration
          cd /home/runner/work/lidar_camera_calibration/catkin_ws
      - uses: actions/checkout@v1
        with:
          path: catkin_ws/lidar_camera_calibration
      - run: echo $PWD
      - run: |
          mv dependencies/aruco_ros ../aruco_ros
          mv dependencies/aruco_mapping ../aruco_mapping
      - run: |
          cd ..
          echo $PWD
          catkin_make -DCATKIN_WHITELIST_PACKAGES="aruco;aruco_ros;aruco_msgs"
          catkin_make -DCATKIN_WHITELIST_PACKAGES="aruco_mapping;lidar_camera_calibration"
          catkin_make -DCATKIN_WHITELIST_PACKAGES=""
