on:
  pull_request:
    branches:
    - master

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
      - name: Setup ROS
        uses: actions/checkout@v1
      - uses: betwo/github-setup-catkin@v1.0.0
        with:
          ros-version: 'melodic'
          workspace: '$GITHUB_WORKSPACE'
      - name: Test ROS installation
        run: |
          catkin_make
