on:
  pull_request:
    branches:
    - master

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@0.0.16
        with:
          required-ros-distributions: melodic
      - name: Test ROS installation
        run: |
          sh /opt/ros/melodic/setup.bash
          rosnode --help

