on:
  pull_request:
    branches:
    - master

jobs:
  build_docker:
    strategy:
      matrix:
        ros_distro : [melodic]
        ros_repo: [main]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup ROS
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{matrix.ros_distro}}
          ROS_REPO: ${{matrix.ros_repo}}
      - run: ls
